
[[plugins]]
  package = "@netlify/plugin-find-and-replace"
  
  [plugins.inputs]
    files = ["**/*.js"]
    
    [[plugins.inputs.replacements]]
      find = "__API_URL__"
      replaceWithEnv = "API_URL"